(() => {
  'use strict';
  const DATA_KEY='cbsleiria.siresp.radios.v1', SETTINGS_KEY='cbsleiria.siresp.settings.v2';
  const TYPES=['Portátil','Móvel','Base'], STATUSES=['Operacional','Manutenção','Reserva','Abatido'];
  const TYPE_ICONS={'Móvel':'🚒'};
  const FORM_FIELDS=['portableNumber','type','issi','serialNumber','brand','model','allocatedTo','status','location','lastMaintenance','nextMaintenance','notes'];
  const COLUMNS=[
    {key:'portableNumber',label:'Rádio Nº'},{key:'type',label:'Tipo'},{key:'issi',label:'ISSI'},{key:'serialNumber',label:'S/N'},
    {key:'brand',label:'Marca'},{key:'model',label:'Modelo'},{key:'allocatedTo',label:'Alocado'},{key:'status',label:'Estado'},
    {key:'location',label:'Localização'},{key:'lastMaintenance',label:'Última manutenção'},{key:'nextMaintenance',label:'Próxima revisão'},{key:'notes',label:'Notas'}
  ];
  const DEFAULT_COLUMNS=COLUMNS.slice(0,9).map(c=>c.key);
  const $=id=>document.getElementById(id), form=$('radio-form'), message=$('message'), body=$('records-body');
  let records=loadRecords(), settings=loadSettings(), sort={key:'portableNumber',dir:1}, pendingDelete=null, currentDetailId=null, sessionUnlocked=false;

  function splitBrandModel(value){const p=String(value||'').trim().split(/\s+/).filter(Boolean);return{brand:p.shift()||'',model:p.join(' ')}}
  function normalizeRecord(record={}){const legacy=splitBrandModel(record.brandModel), r={...record};delete r.brandModel;r.id=String(r.id||uid());r.type=TYPES.includes(r.type)?r.type:'Portátil';r.status=STATUSES.includes(r.status)?r.status:'Operacional';r.brand=typeof r.brand==='string'?r.brand:legacy.brand;r.model=typeof r.model==='string'?r.model:legacy.model;FORM_FIELDS.forEach(k=>r[k]=typeof r[k]==='string'?r[k]:'');if(/^\d{1,4}$/.test(r.portableNumber))r.portableNumber=r.portableNumber.padStart(4,'0');r.history=Array.isArray(r.history)?r.history:[];r.faults=Array.isArray(r.faults)?r.faults:[];r.inventoryStatus=['confirmed','missing','pending'].includes(r.inventoryStatus)?r.inventoryStatus:'pending';return r}
  function loadRecords(){try{const value=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(value)?value.map(normalizeRecord):[]}catch{return[]}}
  function loadSettings(){try{return{exportColumns:DEFAULT_COLUMNS,inventoryStartedAt:null,lastBackup:null,pinHash:null,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return{exportColumns:DEFAULT_COLUMNS,inventoryStartedAt:null,lastBackup:null,pinHash:null}}}
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  function saveRecords(){localStorage.setItem(DATA_KEY,JSON.stringify(records));renderAll()}
  function uid(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
  function now(){return new Date().toISOString()}
  function today(){const d=new Date(),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
  function formattedDate(value,withTime=true){if(!value)return'—';const d=new Date(value.length===10?`${value}T12:00:00`:value);return new Intl.DateTimeFormat('pt-PT',withTime?{dateStyle:'short',timeStyle:'short'}:{dateStyle:'short'}).format(d)}
  function normalized(value){return String(value||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
  function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function statusClass(value){return String(value).replace(/[^A-Za-zÀ-ÿ]/g,'')}
  function show(text,error=false){message.textContent=text;message.classList.toggle('error',error);window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>{message.textContent='';message.classList.remove('error')},5000)}
  function typeIconHtml(type){if(type==='Portátil')return'<img class="type-icon" src="radio-portatil.png" alt="">';if(type==='Base')return'<img class="type-icon" src="radio-base.png" alt="">';return`<span aria-hidden="true">${TYPE_ICONS[type]||''}</span>`}
  function updateTypePreview(selectId,previewId){$(previewId).innerHTML=$(selectId).value?typeIconHtml($(selectId).value):''}
  function setTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id))}
  function appendHistory(record,action,changes=[]){record.history.unshift({at:now(),action,changes})}
  function valuesFromForm(){return Object.fromEntries(FORM_FIELDS.map(k=>[k,$(k).value.trim()]))}
  function uniqueError(data,ignoredId){const other=records.find(r=>r.id!==ignoredId&&(normalized(r.portableNumber)===normalized(data.portableNumber)||normalized(r.issi)===normalized(data.issi)||normalized(r.serialNumber)===normalized(data.serialNumber)));if(!other)return'';if(normalized(other.portableNumber)===normalized(data.portableNumber))return`O Rádio Nº “${data.portableNumber}” já está registado.`;if(normalized(other.issi)===normalized(data.issi))return`O ISSI “${data.issi}” já está registado.`;return`O S/N “${data.serialNumber}” já está registado.`}
  function daysUntil(date){if(!date)return null;return Math.ceil((new Date(`${date}T12:00:00`)-new Date(`${today()}T12:00:00`))/86400000)}
  function nextRadioNumber(){const used=records.map(r=>/^\d{4}$/.test(r.portableNumber)?Number(r.portableNumber):null).filter(n=>n!==null),next=(used.length?Math.max(...used):0)+1;return next<=9999?String(next).padStart(4,'0'):''}
  function typePlaceholders(){const type=$('type').value,location=$('location');location.placeholder=type==='Móvel'?'Ex.: VUCI 01':type==='Base'?'Ex.: Central de Comunicações':'Ex.: Quartel / Viatura';updateTypePreview('type','type-icon-preview')}

  async function pinDigest(pin){const bytes=new TextEncoder().encode(`CBSL-SIRESP:${pin}`),hash=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  async function ensureUnlocked(forcePin=false){if(!settings.pinHash||(!forcePin&&sessionUnlocked))return true;const pin=prompt(forcePin?'Introduza o PIN para confirmar esta ação:':'Introduza o PIN para alterar os dados:');if(pin===null)return false;if(await pinDigest(pin)!==settings.pinHash){show('PIN incorreto.',true);return false}sessionUnlocked=true;renderSecurity();return true}
  async function configureSecurity(){if(settings.pinHash&&!await ensureUnlocked())return;const pin=prompt(settings.pinHash?'Introduza um novo PIN ou deixe vazio para remover a proteção:':'Defina um PIN (mínimo 4 caracteres):');if(pin===null)return;if(!pin){settings.pinHash=null;sessionUnlocked=false;saveSettings();renderSecurity();show('Proteção por PIN removida.');return}if(pin.length<4){show('O PIN deve ter pelo menos 4 caracteres.',true);return}const confirmPin=prompt('Confirme o novo PIN:');if(confirmPin!==pin){show('Os PIN não coincidem.',true);return}settings.pinHash=await pinDigest(pin);sessionUnlocked=true;saveSettings();renderSecurity();show('Proteção por PIN ativada.')}
  function renderSecurity(){$('security-button').textContent=settings.pinHash?(sessionUnlocked?'🔓 Proteção ativa':'🔒 Proteção ativa'):'🔒 Ativar PIN';$('security-button').classList.toggle('security-active',!!settings.pinHash)}

  function filtered(){const q=normalized($('filter-search').value),tp=normalized($('filter-type').value),st=$('filter-status').value,loc=normalized($('filter-location').value),al=normalized($('filter-allocated').value),br=normalized($('filter-brand').value),mo=normalized($('filter-model').value);return records.filter(r=>{const all=normalized(FORM_FIELDS.map(k=>r[k]).join(' '));return(!q||all.includes(q))&&(!tp||normalized(r.type)===tp)&&(!st||r.status===st)&&(!loc||normalized(r.location).includes(loc))&&(!al||normalized(r.allocatedTo).includes(al))&&(!br||normalized(r.brand).includes(br))&&(!mo||normalized(r.model).includes(mo))}).sort((a,b)=>String(a[sort.key]||'').localeCompare(String(b[sort.key]||''),'pt',{numeric:true,sensitivity:'base'})*sort.dir)}
  function updateFilterOptions(){[['location-options','location'],['allocated-options','allocatedTo'],['brand-options','brand'],['model-options','model']].forEach(([listId,field])=>{const values=[...new Set(records.map(r=>r[field].trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt',{sensitivity:'base'}));$(listId).innerHTML=values.map(v=>`<option value="${escapeHtml(v)}"></option>`).join('')});const select=$('filter-type'),selected=select.value;[...select.options].forEach(o=>o.textContent=o.value?`${o.value} (${records.filter(r=>normalized(r.type)===normalized(o.value)).length})`:`Todos (${records.length})`);select.value=selected}
  function renderList(){const list=filtered();$('count-badge').textContent=records.length;$('result-summary').textContent=`${list.length} de ${records.length} equipamento${records.length===1?'':'s'}`;if(!list.length){body.innerHTML=`<tr><td colspan="10" class="empty">${records.length?'Nenhum equipamento corresponde aos filtros.':'Ainda não existem equipamentos registados.'}</td></tr>`;return}body.innerHTML=list.map(r=>{const due=daysUntil(r.nextMaintenance),rowClass=due!==null&&due<0?'maintenance-overdue':due!==null&&due<=30?'maintenance-soon':'';return`<tr class="${rowClass}"><td>${escapeHtml(r.portableNumber)}</td><td><span class="type-badge">${typeIconHtml(r.type)} ${escapeHtml(r.type)}</span></td><td>${escapeHtml(r.issi)}</td><td>${escapeHtml(r.serialNumber)}</td><td>${escapeHtml(r.brand)}</td><td>${escapeHtml(r.model)}</td><td>${escapeHtml(r.allocatedTo)}</td><td><span class="status ${statusClass(r.status)}">${escapeHtml(r.status)}</span></td><td>${escapeHtml(r.location)}</td><td class="actions"><button class="table-button" data-view="${r.id}">Ver</button> <button class="table-button" data-edit="${r.id}">Editar</button> <button class="table-button" data-delete="${r.id}">Eliminar</button></td></tr>`}).join('')}
  function grouped(field){const map=new Map;records.forEach(r=>{const key=r[field]||'Não definido';map.set(key,(map.get(key)||0)+1)});return[...map.entries()].sort((a,b)=>b[1]-a[1])}
  function summaryBars(id,items){const max=Math.max(1,...items.map(x=>x[1]));$(id).innerHTML=items.length?items.slice(0,8).map(([label,count])=>`<div class="summary-row"><span>${escapeHtml(label)}</span><span class="summary-bar"><i style="width:${Math.round(count/max*100)}%"></i></span><strong>${count}</strong></div>`).join(''):'<p class="empty">Sem dados.</p>'}
  function renderDashboard(){const overdue=records.filter(r=>daysUntil(r.nextMaintenance)!==null&&daysUntil(r.nextMaintenance)<0),soon=records.filter(r=>daysUntil(r.nextMaintenance)!==null&&daysUntil(r.nextMaintenance)>=0&&daysUntil(r.nextMaintenance)<=30);$('dashboard-cards').innerHTML=`<div class="summary-card"><strong>${records.length}</strong><span>Total</span></div><div class="summary-card"><strong>${records.filter(r=>r.status==='Operacional').length}</strong><span>Operacionais</span></div><div class="summary-card warning"><strong>${records.filter(r=>r.status==='Manutenção').length}</strong><span>Em manutenção</span></div><div class="summary-card danger-card"><strong>${overdue.length}</strong><span>Revisões vencidas</span></div>`;summaryBars('summary-types',grouped('type'));summaryBars('summary-statuses',grouped('status'));summaryBars('summary-locations',grouped('location'));summaryBars('summary-allocations',grouped('allocatedTo'));const alerts=[...overdue,...soon].sort((a,b)=>String(a.nextMaintenance).localeCompare(String(b.nextMaintenance)));$('maintenance-alerts').innerHTML=alerts.length?alerts.map(r=>`<div class="alert-item ${daysUntil(r.nextMaintenance)<0?'overdue':''}"><span><strong>Rádio ${escapeHtml(r.portableNumber)}</strong> - ${escapeHtml(r.brand)} ${escapeHtml(r.model)}</span><span>${daysUntil(r.nextMaintenance)<0?'Vencida':'Em breve'}: ${formattedDate(r.nextMaintenance,false)}</span></div>`).join(''):'<p>Sem revisões vencidas ou nos próximos 30 dias.</p>';const reminder=$('backup-reminder');if(!settings.lastBackup){reminder.className='backup-reminder';reminder.textContent='Ainda não foi criada uma cópia de segurança.'}else{const days=Math.floor((Date.now()-new Date(settings.lastBackup))/86400000);reminder.className=`backup-reminder ${days<7?'ok':''}`;reminder.textContent=days<7?`Última cópia há ${days} dia(s).`:`Atenção: última cópia de segurança há ${days} dias.`}}

  function renderInventory(){const started=!!settings.inventoryStartedAt,confirmed=records.filter(r=>r.inventoryStatus==='confirmed').length,missing=records.filter(r=>r.inventoryStatus==='missing').length,checked=confirmed+missing,pct=records.length?Math.round(checked/records.length*100):0;$('inventory-summary').textContent=started?`Conferência iniciada em ${formattedDate(settings.inventoryStartedAt)} - ${checked}/${records.length} verificados.`:'Inicie uma conferência para verificar os equipamentos.';$('inventory-progress').innerHTML=started?`<div class="progress-track"><i style="width:${pct}%"></i></div><p>${pct}% concluído · ${confirmed} confirmados · ${missing} em falta</p>`:'';$('inventory-list').innerHTML=started?records.map(r=>`<div class="inventory-item ${r.inventoryStatus}"><div><strong>Rádio ${escapeHtml(r.portableNumber)}</strong> · ${escapeHtml(r.type)} · ${escapeHtml(r.location)}<br><small>${escapeHtml(r.brand)} ${escapeHtml(r.model)} · ISSI ${escapeHtml(r.issi)}</small></div><div class="inventory-actions"><button class="secondary" data-inventory="pending" data-id="${r.id}">Por verificar</button><button class="primary" data-inventory="confirmed" data-id="${r.id}">Confirmado</button><button class="danger" data-inventory="missing" data-id="${r.id}">Em falta</button></div></div>`).join(''):'<p class="empty">Nenhuma conferência ativa.</p>'}
  function renderAll(){updateFilterOptions();renderList();renderDashboard();renderInventory();renderSecurity()}

  function resetEditor(){form.reset();$('record-id').value='';$('portableNumber').value=nextRadioNumber();$('form-title').textContent='Registar equipamento';$('save-button').textContent='Guardar equipamento';$('cancel-edit').classList.add('hidden');setTimeout(typePlaceholders,0)}
  function edit(id){const r=records.find(x=>x.id===id);if(!r)return;FORM_FIELDS.forEach(k=>$(k).value=r[k]||'');$('record-id').value=id;$('form-title').textContent=`Editar equipamento - Rádio Nº ${r.portableNumber}`;$('save-button').textContent='Guardar alterações';$('cancel-edit').classList.remove('hidden');typePlaceholders();setTab('form-panel');window.scrollTo({top:0,behavior:'smooth'})}
  const LABELS={portableNumber:'Rádio Nº',type:'Tipo',issi:'ISSI',serialNumber:'S/N',brand:'Marca',model:'Modelo',brandModel:'Marca / Modelo (anterior)',allocatedTo:'Alocado a',status:'Estado',location:'Localização / Viatura',lastMaintenance:'Última manutenção',nextMaintenance:'Próxima revisão',notes:'Notas'};
  function makeQr(record){try{const qr=qrcode(0,'M'),base=location.href.split('#')[0];qr.addData(`${base}#radio=${encodeURIComponent(record.id)}`);qr.make();return qr.createDataURL(5,4)}catch{return''}}
  function renderFaults(record){$('fault-list').innerHTML=record.faults.length?record.faults.map(f=>`<div class="fault-entry ${f.status==='Resolvida'?'resolved':''}"><strong>${escapeHtml(f.status)} - ${formattedDate(f.date,false)}</strong><small>${escapeHtml(f.description)}</small>${f.provider?`<small>Entidade: ${escapeHtml(f.provider)}</small>`:''}${f.resolution?`<small>Resolução: ${escapeHtml(f.resolution)}</small>`:''}${f.returnDate?`<small>Retorno: ${formattedDate(f.returnDate,false)}</small>`:''}</div>`).join(''):'<p>Sem avarias registadas.</p>'}
  function view(id){const r=records.find(x=>x.id===id);if(!r)return;currentDetailId=id;$('detail-content').innerHTML=`<dl class="detail-grid">${FORM_FIELDS.map(k=>`<div><dt>${LABELS[k]}</dt><dd>${k==='status'?`<span class="status ${statusClass(r[k])}">${escapeHtml(r[k])}</span>`:k==='type'?`<span class="type-badge">${typeIconHtml(r[k])} ${escapeHtml(r[k])}</span>`:k.includes('Maintenance')?formattedDate(r[k],false):escapeHtml(r[k]||'—')}</dd></div>`).join('')}</dl>`;const qr=makeQr(r);$('qr-container').innerHTML=qr?`<img class="qr-image" src="${qr}" alt="QR do equipamento">`:'';renderFaults(r);$('history-list').innerHTML=r.history.length?r.history.map(h=>`<li><strong>${escapeHtml(h.action)}</strong><time>${formattedDate(h.at)}</time>${h.changes?.map(c=>`<div>${escapeHtml(LABELS[c.field]||c.field)}: “${escapeHtml(c.from||'—')}” → “${escapeHtml(c.to||'—')}”</div>`).join('')||''}</li>`).join(''):'<li>Sem eventos registados.</li>';$('detail-dialog').showModal()}

  function download(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function timestampName(){return today()}
  function csvEscape(value){const s=String(value??'');return/[;"\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
  function selectedColumns(){const keys=(settings.exportColumns||DEFAULT_COLUMNS).filter(k=>COLUMNS.some(c=>c.key===k));return COLUMNS.filter(c=>keys.includes(c.key))}
  function exportCsv(){const cols=selectedColumns(),csv=[cols.map(c=>c.label).join(';'),...filtered().map(r=>cols.map(c=>csvEscape(r[c.key])).join(';'))].join('\r\n');download(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`radios-siresp-${timestampName()}.csv`);show('CSV exportado com sucesso.')}
  function exportJson(){settings.lastBackup=now();saveSettings();download(new Blob([JSON.stringify({application:'Registo Rádios Comunicações SIRESP',version:3,exportedAt:now(),records},null,2)],{type:'application/json'}),`copia-radios-siresp-${timestampName()}.json`);renderDashboard();show('Cópia de segurança criada.')}
  function filterDescription(){const map=[['filter-search','Pesquisa'],['filter-type','Tipo'],['filter-status','Estado'],['filter-location','Localização'],['filter-allocated','Alocado'],['filter-brand','Marca'],['filter-model','Modelo']];const applied=map.map(([id,label])=>[$(id).value.trim(),label]).filter(x=>x[0]).map(([v,l])=>`${l}: ${v}`);return applied.length?applied.join(' | '):'Sem filtros aplicados'}
  async function logoJpeg(){const image=document.querySelector('.logo');try{await image.decode()}catch{}const c=document.createElement('canvas');c.width=110;c.height=110;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,110,110);ctx.drawImage(image,0,0,110,110);return{data:atob(c.toDataURL('image/jpeg',.9).split(',')[1]),width:110,height:110}}
  function pdfText(value){return String(value??'').replace(/[–—]/g,'-').replace(/…/g,'...').replace(/[\\()]/g,'\\$&').replace(/[\r\n]+/g,' ')}
  function trimPdf(value,n){const s=String(value??'');return s.length>n?`${s.slice(0,Math.max(0,n-3))}...`:s}
  function finishPdf(objects,filename){let out='%PDF-1.4\n%âãÏÓ\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=out.length;const obj=objects[i];if(obj&&typeof obj==='object'){const d=obj.image.data;out+=`${i} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${obj.image.width} /Height ${obj.image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${d.length} >>\nstream\n${d}\nendstream\nendobj\n`}else out+=`${i} 0 obj\n${obj}\nendobj\n`}const xref=out.length;out+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const bytes=new Uint8Array(out.length);for(let i=0;i<out.length;i++)bytes[i]=out.charCodeAt(i)&255;download(new Blob([bytes],{type:'application/pdf'}),filename)}
  async function exportPdf(){const list=filtered();if(!list.length){show('Não existem registos para incluir no PDF.',true);return}let image=null;try{image=await logoJpeg()}catch{}const cols=selectedColumns(),pages=[];for(let i=0;i<list.length;i+=18)pages.push(list.slice(i,i+18));const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]=`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map((_,i)=>`${5+i*2} 0 R`).join(' ')}] >>`;objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';objects[4]=image?{image}:'<< >>';const width=Math.floor(515/cols.length),max=Math.max(5,Math.floor(width/5));pages.forEach((rows,i)=>{const pn=5+i*2,cn=pn+1,img=image?' /XObject << /Im1 4 0 R >>':'';objects[pn]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >>${img} >> /Contents ${cn} 0 R >>`;let c=image?'q 52 0 0 52 40 758 cm /Im1 Do Q\n':'';c+=`BT /F1 17 Tf 105 797 Td (${pdfText('Registo Rádios Comunicações SIRESP')}) Tj ET\nBT /F1 10 Tf 105 781 Td (CBSLeiria) Tj ET\nBT /F1 7 Tf 40 750 Td (${pdfText(`Emitido: ${formattedDate(now())} | ${filterDescription()}`)}) Tj ET\n`;let x=40;cols.forEach(col=>{c+=`0.16 0.20 0.24 rg ${x} 720 ${width} 18 re f 1 1 1 rg BT /F1 6 Tf ${x+2} 726 Td (${pdfText(trimPdf(col.label,max))}) Tj ET\n`;x+=width});rows.forEach((r,row)=>{let xx=40,y=704-row*25;cols.forEach(col=>{c+=`0.92 0.94 0.96 rg ${xx} ${y-4} ${width} 24 re f 0.1 0.13 0.17 rg BT /F1 6 Tf ${xx+2} ${y+7} Td (${pdfText(trimPdf(r[col.key],max))}) Tj ET\n`;xx+=width})});c+=`BT /F1 8 Tf 40 35 Td (${pdfText(`Página ${i+1} de ${pages.length} - ${list.length} equipamento(s)`)}) Tj ET\n`;objects[cn]=`<< /Length ${c.length} >>\nstream\n${c}endstream`});finishPdf(objects,`listagem-radios-siresp-${timestampName()}.pdf`);show('PDF criado com sucesso.')}
  function exportIndividualPdf(){const r=records.find(x=>x.id===currentDetailId);if(!r)return;const lines=[...COLUMNS.map(c=>`${c.label}: ${r[c.key]||'-'}`),...r.faults.flatMap(f=>[`Avaria ${formattedDate(f.date,false)} - ${f.status}: ${f.description}`])];let c=`BT /F1 18 Tf 50 790 Td (${pdfText(`Ficha do Rádio Nº ${r.portableNumber}`)}) Tj ET\nBT /F1 10 Tf 50 772 Td (CBSLeiria - SIRESP) Tj ET\n`;lines.slice(0,32).forEach((line,i)=>c+=`BT /F1 9 Tf 50 ${744-i*21} Td (${pdfText(trimPdf(line,92))}) Tj ET\n`);const objects=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [4 0 R] >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents 5 0 R >>',`<< /Length ${c.length} >>\nstream\n${c}endstream`];finishPdf(objects,`ficha-radio-${r.portableNumber}-${timestampName()}.pdf`)}

  function parseCsv(text){const first=(text.split(/\r?\n/)[0]||''),sep=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===sep&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
  async function parseXlsx(file){const zip=await JSZip.loadAsync(await file.arrayBuffer()),shared=[];if(zip.file('xl/sharedStrings.xml')){const doc=new DOMParser().parseFromString(await zip.file('xl/sharedStrings.xml').async('text'),'application/xml');[...doc.getElementsByTagName('si')].forEach(si=>shared.push([...si.getElementsByTagName('t')].map(t=>t.textContent).join('')))}const wb=new DOMParser().parseFromString(await zip.file('xl/workbook.xml').async('text'),'application/xml'),sheet=wb.getElementsByTagName('sheet')[0],rid=sheet?.getAttribute('r:id'),rels=new DOMParser().parseFromString(await zip.file('xl/_rels/workbook.xml.rels').async('text'),'application/xml'),rel=[...rels.getElementsByTagName('Relationship')].find(x=>x.getAttribute('Id')===rid),target=rel?.getAttribute('Target')||'worksheets/sheet1.xml',path=target.startsWith('/')?target.slice(1):`xl/${target.replace(/^\.\//,'')}`,xml=await zip.file(path).async('text'),doc=new DOMParser().parseFromString(xml,'application/xml'),rows=[];[...doc.getElementsByTagName('row')].forEach(rowEl=>{const row=[];[...rowEl.getElementsByTagName('c')].forEach(c=>{const ref=c.getAttribute('r')||'A1';let col=0;for(const ch of ref.match(/[A-Z]+/)[0])col=col*26+ch.charCodeAt(0)-64;const type=c.getAttribute('t'),v=c.getElementsByTagName('v')[0]?.textContent||'',inline=[...c.getElementsByTagName('t')].map(t=>t.textContent).join('');row[col-1]=type==='s'?shared[Number(v)]||'':type==='inlineStr'?inline:v});rows.push(row.map(x=>x??''))});return rows}
  function importedRecords(rows){if(rows.length<2)return[];const headers=rows[0].map(normalized),find=(aliases)=>headers.findIndex(h=>aliases.some(a=>h===normalized(a))),indexes={portableNumber:find(['Rádio Nº','Portátil Nº','Radio']),type:find(['Tipo']),issi:find(['ISSI']),serialNumber:find(['S/N','SN','Número de série']),brand:find(['Marca']),model:find(['Modelo']),brandModel:find(['Marca / Modelo']),allocatedTo:find(['Alocado','Alocado a']),status:find(['Estado']),location:find(['Localização','Localização / Viatura']),notes:find(['Notas']),lastMaintenance:find(['Última manutenção']),nextMaintenance:find(['Próxima revisão'])};return rows.slice(1).map(row=>{const get=k=>indexes[k]>=0?String(row[indexes[k]]??'').trim():'';const legacy=splitBrandModel(get('brandModel'));return normalizeRecord({id:uid(),portableNumber:get('portableNumber'),type:get('type'),issi:get('issi'),serialNumber:get('serialNumber'),brand:get('brand')||legacy.brand,model:get('model')||legacy.model,allocatedTo:get('allocatedTo'),status:get('status'),location:get('location'),notes:get('notes'),lastMaintenance:get('lastMaintenance'),nextMaintenance:get('nextMaintenance'),createdAt:now(),updatedAt:now(),history:[{at:now(),action:'Importado de ficheiro',changes:[]}]})}).filter(r=>r.portableNumber&&r.issi&&r.serialNumber)}
  async function importTable(file){if(!await ensureUnlocked())return;try{const rows=file.name.toLowerCase().endsWith('.xlsx')?await parseXlsx(file):parseCsv(await file.text()),incoming=importedRecords(rows);let added=0,skipped=0;for(const r of incoming){if(uniqueError(r,'')){skipped++;continue}records.push(r);added++}saveRecords();show(`Importação concluída: ${added} adicionados, ${skipped} duplicados ignorados.`)}catch(error){show(`Não foi possível importar o ficheiro: ${error.message||'formato inválido'}.`,true)}}

  function openColumns(){const selected=new Set(settings.exportColumns||DEFAULT_COLUMNS);$('column-options').innerHTML=COLUMNS.map(c=>`<label><input type="checkbox" value="${c.key}" ${selected.has(c.key)?'checked':''}> ${c.label}</label>`).join('');$('columns-dialog').showModal()}
  function saveColumns(){const keys=[...$('column-options').querySelectorAll('input:checked')].map(x=>x.value);if(!keys.length){show('Selecione pelo menos uma coluna.',true);return}settings.exportColumns=keys;saveSettings();$('columns-dialog').close();show('Colunas de exportação atualizadas.')}
  function printQr(){const r=records.find(x=>x.id===currentDetailId),src=r&&makeQr(r);if(!r||!src)return;const w=window.open('','_blank','width=500,height=650');if(!w){show('O navegador bloqueou a janela de impressão.',true);return}w.document.write(`<!doctype html><title>Etiqueta Rádio ${escapeHtml(r.portableNumber)}</title><style>body{text-align:center;font-family:Arial;padding:25px}.label{border:2px solid #111;padding:18px;display:inline-block}img{width:260px}.n{font-size:26px;font-weight:bold}</style><div class="label"><div class="n">Rádio ${escapeHtml(r.portableNumber)}</div><p>${escapeHtml(r.type)} · ${escapeHtml(r.brand)} ${escapeHtml(r.model)}</p><img src="${src}"><p>ISSI ${escapeHtml(r.issi)}</p><strong>CBSLeiria · SIRESP</strong></div><script>onload=()=>print()<\/script>`);w.document.close()}

  form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity()||!await ensureUnlocked())return;const data=valuesFromForm(),id=$('record-id').value,error=uniqueError(data,id);if(error){show(error,true);return}if(id){const r=records.find(x=>x.id===id),changes=FORM_FIELDS.filter(k=>r[k]!==data[k]).map(k=>({field:k,from:r[k],to:data[k]}));Object.assign(r,data,{updatedAt:now()});if(changes.length)appendHistory(r,'Alteração de equipamento',changes)}else{const r=normalizeRecord({id:uid(),...data,createdAt:now(),updatedAt:now(),history:[],faults:[]});appendHistory(r,'Equipamento registado');records.unshift(r)}saveRecords();resetEditor();show(id?'Equipamento atualizado.':'Equipamento registado com sucesso.')});
  form.addEventListener('reset',()=>setTimeout(typePlaceholders,0));
  body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)view(b.dataset.view);if(b.dataset.edit)edit(b.dataset.edit);if(b.dataset.delete){pendingDelete=b.dataset.delete;$('confirm-dialog').showModal()}});
  document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.panel)));document.querySelectorAll('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{sort={key:th.dataset.sort,dir:sort.key===th.dataset.sort?-sort.dir:1};renderList()}));
  ['filter-search','filter-status','filter-location','filter-allocated','filter-brand','filter-model'].forEach(id=>$(id).addEventListener(id==='filter-status'?'change':'input',renderList));['change','input'].forEach(ev=>$('filter-type').addEventListener(ev,()=>{updateTypePreview('filter-type','filter-type-icon-preview');renderList()}));
  $('clear-filters').addEventListener('click',()=>{['filter-search','filter-type','filter-status','filter-location','filter-allocated','filter-brand','filter-model'].forEach(id=>$(id).value='');updateTypePreview('filter-type','filter-type-icon-preview');renderList()});$('type').addEventListener('change',typePlaceholders);$('cancel-edit').addEventListener('click',resetEditor);$('go-new-record').addEventListener('click',()=>setTab('form-panel'));
  $('export-csv').addEventListener('click',exportCsv);$('export-json').addEventListener('click',exportJson);$('export-pdf').addEventListener('click',()=>exportPdf().catch(()=>show('Não foi possível criar o PDF.',true)));$('column-settings').addEventListener('click',openColumns);$('save-columns').addEventListener('click',saveColumns);document.querySelectorAll('[data-close-columns]').forEach(b=>b.addEventListener('click',()=>$('columns-dialog').close()));
  $('import-table').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';if(file)importTable(file)});
  $('import-json').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file||!await ensureUnlocked())return;try{const parsed=JSON.parse(await file.text());let incoming=Array.isArray(parsed)?parsed:parsed.records;if(!Array.isArray(incoming))throw new Error;if(!confirm(`Restaurar ${incoming.length} equipamento(s)? Os dados atuais serão substituídos.`))return;records=incoming.map(normalizeRecord);saveRecords();resetEditor();show('Cópia de segurança restaurada.')}catch{show('Cópia JSON inválida.',true)}});
  $('confirm-delete').addEventListener('click',async()=>{if(!pendingDelete||!await ensureUnlocked(true))return;records=records.filter(r=>r.id!==pendingDelete);pendingDelete=null;$('confirm-dialog').close();saveRecords();show('Equipamento eliminado.')});$('cancel-delete').addEventListener('click',()=>{$('confirm-dialog').close();pendingDelete=null});
  document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>$('detail-dialog').close()));$('print-qr').addEventListener('click',printQr);$('individual-pdf').addEventListener('click',exportIndividualPdf);$('add-fault').addEventListener('click',()=>{$('fault-form').reset();$('fault-date').value=today();$('fault-dialog').showModal()});document.querySelectorAll('[data-close-fault]').forEach(b=>b.addEventListener('click',()=>$('fault-dialog').close()));
  $('fault-form').addEventListener('submit',async e=>{e.preventDefault();if(!await ensureUnlocked())return;const r=records.find(x=>x.id===currentDetailId);if(!r)return;r.faults.unshift({id:uid(),date:$('fault-date').value,status:$('fault-status').value,description:$('fault-description').value.trim(),provider:$('fault-provider').value.trim(),returnDate:$('fault-return-date').value,resolution:$('fault-resolution').value.trim()});if($('fault-status').value!=='Resolvida')r.status='Manutenção';appendHistory(r,'Avaria/reparação registada');$('fault-dialog').close();saveRecords();view(r.id);show('Avaria/reparação registada.')});
  $('start-inventory').addEventListener('click',async()=>{if(!await ensureUnlocked()||!confirm('Iniciar uma nova conferência? O estado da conferência anterior será limpo.'))return;records.forEach(r=>r.inventoryStatus='pending');settings.inventoryStartedAt=now();saveSettings();saveRecords()});$('clear-inventory').addEventListener('click',async()=>{if(!settings.inventoryStartedAt||!await ensureUnlocked())return;settings.inventoryStartedAt=null;saveSettings();renderInventory()});$('inventory-list').addEventListener('click',async e=>{const b=e.target.closest('[data-inventory]');if(!b||!await ensureUnlocked())return;const r=records.find(x=>x.id===b.dataset.id);if(r){r.inventoryStatus=b.dataset.inventory;saveRecords()}});
  $('security-button').addEventListener('click',configureSecurity);
  if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});
  $('portableNumber').value=nextRadioNumber();typePlaceholders();updateTypePreview('filter-type','filter-type-icon-preview');renderAll();const hashId=location.hash.match(/radio=([^&]+)/)?.[1];if(hashId){const id=decodeURIComponent(hashId);setTimeout(()=>{if(records.some(r=>r.id===id)){setTab('list-panel');view(id)}},0)}
})();
