(() => {
  'use strict';
  const DATA_KEY='cbsleiria.siresp.radios.v1', SETTINGS_KEY='cbsleiria.siresp.settings.v2', GITHUB_TOKEN_KEY='cbsleiria.siresp.githubPublicationToken.v1', GITHUB_REPOSITORY_KEY='cbsleiria.siresp.githubPublicationRepository.v1';
  const SYSTEMS=['SIRESP','ROB'], TYPES=['Portátil','Móvel','Base'], STATUSES=['Operacional','Manutenção','Reserva','Abatido'];
  const TYPE_ICONS={'Móvel':'🚒'};
  const FORM_FIELDS=['portableNumber','type','issi','serialNumber','brand','model','allocatedTo','network','status','location','lastMaintenance','nextMaintenance','notes'];
  const COLUMNS=[
    {key:'portableNumber',label:'Rádio Nº'},{key:'type',label:'Tipo'},{key:'issi',label:'ISSI'},{key:'serialNumber',label:'S/N'},
    {key:'brand',label:'Marca'},{key:'model',label:'Modelo'},{key:'allocatedTo',label:'Alocado'},{key:'network',label:'Redes'},{key:'status',label:'Estado'},
    {key:'location',label:'Localização'},{key:'lastMaintenance',label:'Última manutenção'},{key:'nextMaintenance',label:'Próxima revisão'},{key:'notes',label:'Notas'}
  ];
  const DEFAULT_COLUMNS=COLUMNS.slice(0,10).map(c=>c.key);
  const $=id=>document.getElementById(id), form=$('radio-form'), message=$('message'), body=$('records-body');
  let records=loadRecords(), settings=loadSettings(), currentSystem=SYSTEMS.includes(settings.currentSystem)?settings.currentSystem:'SIRESP', sort={key:'portableNumber',dir:1}, pendingDelete=null, currentDetailId=null, sessionUnlocked=false;

  function splitBrandModel(value){const p=String(value||'').trim().split(/\s+/).filter(Boolean);return{brand:p.shift()||'',model:p.join(' ')}}
  function usesRadioNumber(record){return record.type==='Portátil'&&record.allocatedTo==='CBSL'}
  function normalizeRecord(record={}){const legacy=splitBrandModel(record.brandModel), r={...record};delete r.brandModel;r.id=String(r.id||uid());r.system=SYSTEMS.includes(r.system)?r.system:'SIRESP';r.type=TYPES.includes(r.type)?r.type:'Portátil';r.status=STATUSES.includes(r.status)?r.status:'Operacional';r.brand=typeof r.brand==='string'?r.brand:legacy.brand;r.model=typeof r.model==='string'?r.model:legacy.model;FORM_FIELDS.forEach(k=>r[k]=typeof r[k]==='string'?r[k]:'');if(/^\d{1,4}$/.test(r.portableNumber))r.portableNumber=r.portableNumber.padStart(4,'0');if(!usesRadioNumber(r))r.portableNumber='';if(r.system==='ROB')r.issi='';r.history=Array.isArray(r.history)?r.history:[];r.faults=Array.isArray(r.faults)?r.faults:[];r.inventoryStatus=['confirmed','missing','pending'].includes(r.inventoryStatus)?r.inventoryStatus:'pending';return r}
  function loadRecords(){try{const value=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(value)?value.map(normalizeRecord):[]}catch{return[]}}
  function loadSettings(){try{const saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return{exportColumns:DEFAULT_COLUMNS,exportColumnsBySystem:{SIRESP:saved.exportColumns||DEFAULT_COLUMNS,ROB:DEFAULT_COLUMNS.filter(k=>k!=='issi')},inventoryStartedAt:null,inventoryStartedAtBySystem:{SIRESP:saved.inventoryStartedAt||null,ROB:null},lastBackup:null,pinHash:null,currentSystem:'SIRESP',...saved,exportColumnsBySystem:{SIRESP:saved.exportColumnsBySystem?.SIRESP??saved.exportColumns??DEFAULT_COLUMNS,ROB:saved.exportColumnsBySystem?.ROB??DEFAULT_COLUMNS.filter(k=>k!=='issi')},inventoryStartedAtBySystem:{SIRESP:saved.inventoryStartedAtBySystem?.SIRESP??saved.inventoryStartedAt??null,ROB:saved.inventoryStartedAtBySystem?.ROB??null}}}catch{return{exportColumns:DEFAULT_COLUMNS,exportColumnsBySystem:{SIRESP:DEFAULT_COLUMNS,ROB:DEFAULT_COLUMNS.filter(k=>k!=='issi')},inventoryStartedAt:null,inventoryStartedAtBySystem:{SIRESP:null,ROB:null},lastBackup:null,pinHash:null,currentSystem:'SIRESP'}}}
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  function saveRecords(){localStorage.setItem(DATA_KEY,JSON.stringify(records));renderAll()}
  function uid(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
  function now(){return new Date().toISOString()}
  function today(){const d=new Date(),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
  function formattedDate(value,withTime=true){if(!value)return'—';const d=new Date(value.length===10?`${value}T12:00:00`:value);return new Intl.DateTimeFormat('pt-PT',withTime?{dateStyle:'short',timeStyle:'short'}:{dateStyle:'short'}).format(d)}
  function normalized(value){return String(value||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
  function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function listLogoHtml(name){
  const logos={motorola:['motorola.webp','Motorola',90,20],sepura:['sepura.webp','Sepura',64,20],anepc:['anepc.webp','ANEPC',24,24],municipal:['leiria-brasao.webp','Município de Leiria',24,26]};
  const logo=logos[name];return logo?`<img class="list-logo list-logo-${name}" src="${logo[0]}" alt="${logo[1]}" title="${logo[1]}" width="${logo[2]}" height="${logo[3]}" style="width:${logo[2]}px;height:${logo[3]}px;object-fit:contain;vertical-align:middle;flex-shrink:0">`:'';
}
function brandCellHtml(value){const key=normalized(value),icon=key==='motorola'?'motorola':key==='sepura'?'sepura':'';return icon?`<span class="list-with-logo">${listLogoHtml(icon)}</span>`:escapeHtml(value)}
function networkCellHtml(value){const key=normalized(value),icons=key==='dupla'?['municipal','anepc']:[key];return `<span class="list-with-logo">${icons.map(listLogoHtml).join('')}<span>${escapeHtml(value)}</span></span>`}
  function statusClass(value){return String(value).replace(/[^A-Za-zÀ-ÿ]/g,'')}
  function show(text,error=false){message.textContent=text;message.classList.toggle('error',error);window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>{message.textContent='';message.classList.remove('error')},5000)}
  function typeIconHtml(type){if(type==='Portátil')return'<img class="type-icon" src="radio-portatil.png" alt="">';if(type==='Base')return'<img class="type-icon" src="radio-base.png" alt="">';return`<span aria-hidden="true">${TYPE_ICONS[type]||''}</span>`}
  function updateTypePreview(selectId,previewId){$(previewId).innerHTML=$(selectId).value?typeIconHtml($(selectId).value):''}
  function setTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id))}
  function activeRecords(){return records.filter(r=>r.system===currentSystem)}
  function fieldsForSystem(system=currentSystem){return FORM_FIELDS.filter(k=>system!=='ROB'||k!=='issi')}
  function columnsForSystem(system=currentSystem){return COLUMNS.filter(c=>system!=='ROB'||c.key!=='issi')}
  function appendHistory(record,action,changes=[]){record.history.unshift({at:now(),action,changes})}
  function valuesFromForm(){const data=Object.fromEntries(FORM_FIELDS.map(k=>[k,$(k).value.trim()]));data.system=currentSystem;if(!usesRadioNumber(data))data.portableNumber='';if(currentSystem==='ROB')data.issi='';return data}
  function uniqueError(data,ignoredId){
    const system=SYSTEMS.includes(data.system)?data.system:currentSystem;
    const number=v=>/^\d+$/.test(String(v).trim())?String(Number(v)):normalized(v);
    const others=records.filter(r=>r.id!==ignoredId&&r.system===system);
    if(data.type==='Portátil'&&data.status!=='Abatido'&&data.portableNumber&&others.some(r=>r.type==='Portátil'&&r.status!=='Abatido'&&number(r.portableNumber)===number(data.portableNumber)))return`O Rádio Nº “${data.portableNumber}” já está atribuído a outro portátil não abatido em ${system}.`;
    if(data.issi&&others.some(r=>normalized(r.issi)===normalized(data.issi)))return`O ISSI “${data.issi}” já está registado em ${system}.`;
    if(data.serialNumber&&others.some(r=>normalized(r.serialNumber)===normalized(data.serialNumber)))return`O S/N “${data.serialNumber}” já está registado em ${system}.`;
    return '';
  }
  function daysUntil(date){if(!date)return null;return Math.ceil((new Date(`${date}T12:00:00`)-new Date(`${today()}T12:00:00`))/86400000)}
  function nextRadioNumber(){const used=activeRecords().filter(r=>r.type==='Portátil'&&r.status!=='Abatido').map(r=>/^\d{4}$/.test(r.portableNumber)?Number(r.portableNumber):null).filter(n=>n!==null),next=(used.length?Math.max(...used):0)+1;return next<=9999?String(next).padStart(4,'0'):''}
  function updateAllocationRules(){const radio=$('portableNumber'),portable=usesRadioNumber({type:$('type').value,allocatedTo:$('allocatedTo').value});$('allocatedTo').disabled=false;radio.required=portable;radio.disabled=!portable;$('portable-number-required').classList.toggle('hidden',!portable);if(portable){if(!radio.value)radio.value=nextRadioNumber();radio.placeholder='Ex.: 0012';$('portable-number-hint').textContent='Número do portátil: sugestão automática editável. Pode reutilizar números de portáteis abatidos.'}else{radio.value='';radio.placeholder='Não aplicável';$('portable-number-hint').textContent='Apenas os rádios portáteis alocados à CBSL têm número sequencial.'}}

  function updateSystemUi(){document.body.dataset.system=currentSystem;document.querySelectorAll('button[data-system]').forEach(b=>{const active=b.dataset.system===currentSystem;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const rob=currentSystem==='ROB';$('issi-field').classList.toggle('hidden',rob);$('issi').required=!rob;$('issi').disabled=rob;if(rob)$('issi').value='';if(!$('record-id').value)$('form-title').textContent=`Registar equipamento ${currentSystem}`;$('filter-search').placeholder=rob?'Rádio Nº, S/N, marca, modelo…':'Rádio Nº, ISSI, S/N, marca, modelo…';document.querySelectorAll('.issi-column').forEach(x=>x.classList.toggle('hidden',rob));updateAllocationRules()}
  function clearFilters(){['filter-search','filter-type','filter-status','filter-location','filter-allocated','filter-brand','filter-model','filter-network'].forEach(id=>$(id).value='');updateTypePreview('filter-type','filter-type-icon-preview')}
  function switchSystem(system){if(!SYSTEMS.includes(system)||system===currentSystem)return;currentSystem=system;settings.currentSystem=system;saveSettings();sort={key:'portableNumber',dir:1};clearFilters();resetEditor();updateSystemUi();renderAll()}
  function typePlaceholders(){updateAllocationRules();const type=$('type').value,location=$('location');location.placeholder=type==='Móvel'?'Ex.: VUCI 01':type==='Base'?'Ex.: Central de Comunicações':'Ex.: Quartel / Viatura';updateTypePreview('type','type-icon-preview')}

  async function pinDigest(pin){const bytes=new TextEncoder().encode(`CBSL-SIRESP:${pin}`),hash=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  async function ensureUnlocked(forcePin=false){if(!settings.pinHash||(!forcePin&&sessionUnlocked))return true;const pin=prompt(forcePin?'Introduza o PIN para confirmar esta ação:':'Introduza o PIN para alterar os dados:');if(pin===null)return false;if(await pinDigest(pin)!==settings.pinHash){show('PIN incorreto.',true);return false}sessionUnlocked=true;renderSecurity();return true}
  async function configureSecurity(){if(settings.pinHash&&!await ensureUnlocked())return;const pin=prompt(settings.pinHash?'Introduza um novo PIN ou deixe vazio para remover a proteção:':'Defina um PIN (mínimo 4 caracteres):');if(pin===null)return;if(!pin){settings.pinHash=null;sessionUnlocked=false;saveSettings();renderSecurity();show('Proteção por PIN removida.');return}if(pin.length<4){show('O PIN deve ter pelo menos 4 caracteres.',true);return}const confirmPin=prompt('Confirme o novo PIN:');if(confirmPin!==pin){show('Os PIN não coincidem.',true);return}settings.pinHash=await pinDigest(pin);sessionUnlocked=true;saveSettings();renderSecurity();show('Proteção por PIN ativada.')}
  function renderSecurity(){$('security-button').textContent=settings.pinHash?(sessionUnlocked?'🔓 Proteção ativa':'🔒 Proteção ativa'):'🔒 Ativar PIN';$('security-button').classList.toggle('security-active',!!settings.pinHash)}

  function compareRecords(a,b){
    const av=String(a[sort.key]??'').trim(),bv=String(b[sort.key]??'').trim();
    if(sort.key==='portableNumber'&&(!av||!bv)){if(!av&&bv)return 1;if(av&&!bv)return -1;return String(a.type??'').localeCompare(String(b.type??''),'pt',{numeric:true,sensitivity:'base'})}
    return av.localeCompare(bv,'pt',{numeric:true,sensitivity:'base'})*sort.dir;
  }
  function filtered(){const q=normalized($('filter-search').value),tp=normalized($('filter-type').value),st=$('filter-status').value,loc=normalized($('filter-location').value),al=normalized($('filter-allocated').value),br=normalized($('filter-brand').value),mo=normalized($('filter-model').value);return activeRecords().filter(r=>{const all=normalized(fieldsForSystem().map(k=>r[k]).join(' '));return(!$('filter-network').value||r.network===$('filter-network').value)&&(!q||all.includes(q))&&(!tp||normalized(r.type)===tp)&&(!st||r.status===st)&&(!loc||normalized(r.location).includes(loc))&&(!al||normalized(r.allocatedTo).includes(al))&&(!br||normalized(r.brand).includes(br))&&(!mo||normalized(r.model).includes(mo))}).sort(compareRecords)}
  function updateFilterOptions(){const current=activeRecords();[['location-options','location'],['allocated-options','allocatedTo'],['brand-options','brand'],['model-options','model']].forEach(([listId,field])=>{const values=[...new Set(current.map(r=>r[field].trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt',{sensitivity:'base'}));$(listId).innerHTML=values.map(v=>`<option value="${escapeHtml(v)}"></option>`).join('')});const select=$('filter-type'),selected=select.value;[...select.options].forEach(o=>o.textContent=o.value?`${o.value} (${current.filter(r=>normalized(r.type)===normalized(o.value)).length})`:`Todos (${current.length})`);select.value=selected}
  function renderList(){const current=activeRecords(),list=filtered(),showIssi=currentSystem==='SIRESP',colspan=showIssi?11:10;$('count-badge').textContent=current.length;$('result-summary').textContent=`${list.length} de ${current.length} equipamento${current.length===1?'':'s'} ${currentSystem}`;if(!list.length){body.innerHTML=`<tr><td colspan="${colspan}" class="empty">${current.length?'Nenhum equipamento corresponde aos filtros.':`Ainda não existem equipamentos ${currentSystem} registados.`}</td></tr>`;return}body.innerHTML=list.map(r=>{const due=daysUntil(r.nextMaintenance),rowClass=due!==null&&due<0?'maintenance-overdue':due!==null&&due<=30?'maintenance-soon':'';return`<tr class="${rowClass}"><td>${escapeHtml(r.portableNumber||'—')}</td><td><span class="type-badge">${typeIconHtml(r.type)} ${escapeHtml(r.type)}</span></td>${showIssi?`<td>${escapeHtml(r.issi)}</td>`:''}<td>${escapeHtml(r.serialNumber)}</td><td>${brandCellHtml(r.brand)}</td><td>${escapeHtml(r.model)}</td><td>${escapeHtml(r.allocatedTo)}</td><td>${networkCellHtml(r.network)}</td><td><span class="status ${statusClass(r.status)}">${escapeHtml(r.status)}</span></td><td>${escapeHtml(r.location)}</td><td class="actions"><button class="table-button action-icon" data-view="${r.id}" title="Ver equipamento" aria-label="Ver equipamento">⌕</button><button class="table-button action-icon" data-edit="${r.id}" title="Editar equipamento" aria-label="Editar equipamento">✎</button><button class="table-button action-icon danger-icon" data-delete="${r.id}" title="Eliminar equipamento" aria-label="Eliminar equipamento">×</button></td></tr>`}).join('')}
  function grouped(field){const map=new Map;activeRecords().forEach(r=>{const key=r[field]||'Não definido';map.set(key,(map.get(key)||0)+1)});return[...map.entries()].sort((a,b)=>b[1]-a[1])}
  function summaryBars(id,items){const max=Math.max(1,...items.map(x=>x[1]));$(id).innerHTML=items.length?items.slice(0,8).map(([label,count])=>`<div class="summary-row"><span>${escapeHtml(label)}</span><span class="summary-bar"><i style="width:${Math.round(count/max*100)}%"></i></span><strong>${count}</strong></div>`).join(''):'<p class="empty">Sem dados.</p>'}
  function renderDashboard(){const current=activeRecords(),overdue=current.filter(r=>daysUntil(r.nextMaintenance)!==null&&daysUntil(r.nextMaintenance)<0),soon=current.filter(r=>daysUntil(r.nextMaintenance)!==null&&daysUntil(r.nextMaintenance)>=0&&daysUntil(r.nextMaintenance)<=30);$('dashboard-cards').innerHTML=`<div class="summary-card"><strong>${current.length}</strong><span>Total ${currentSystem}</span></div><div class="summary-card"><strong>${current.filter(r=>r.status==='Operacional').length}</strong><span>Operacionais</span></div><div class="summary-card warning"><strong>${current.filter(r=>r.status==='Manutenção').length}</strong><span>Em manutenção</span></div><div class="summary-card danger-card"><strong>${overdue.length}</strong><span>Revisões vencidas</span></div>`;summaryBars('summary-types',grouped('type'));summaryBars('summary-statuses',grouped('status'));summaryBars('summary-locations',grouped('location'));summaryBars('summary-allocations',grouped('allocatedTo'));const alerts=[...overdue,...soon].sort((a,b)=>String(a.nextMaintenance).localeCompare(String(b.nextMaintenance)));$('maintenance-alerts').innerHTML=alerts.length?alerts.map(r=>`<div class="alert-item ${daysUntil(r.nextMaintenance)<0?'overdue':''}"><span><strong>Rádio ${escapeHtml(r.portableNumber||'sem Nº')}</strong> - ${escapeHtml(r.brand)} ${escapeHtml(r.model)}</span><span>${daysUntil(r.nextMaintenance)<0?'Vencida':'Em breve'}: ${formattedDate(r.nextMaintenance,false)}</span></div>`).join(''):'<p>Sem revisões vencidas ou nos próximos 30 dias.</p>';const reminder=$('backup-reminder');if(!settings.lastBackup){reminder.className='backup-reminder';reminder.textContent='Ainda não foi criada uma cópia de segurança.'}else{const days=Math.floor((Date.now()-new Date(settings.lastBackup))/86400000);reminder.className=`backup-reminder ${days<7?'ok':''}`;reminder.textContent=days<7?`Última cópia há ${days} dia(s).`:`Atenção: última cópia de segurança há ${days} dias.`}}

  function renderInventory(){const inventoryRecords=activeRecords().filter(r=>r.allocatedTo==='CBSL'),startedAt=settings.inventoryStartedAtBySystem?.[currentSystem],started=!!startedAt,confirmed=inventoryRecords.filter(r=>r.inventoryStatus==='confirmed').length,missing=inventoryRecords.filter(r=>r.inventoryStatus==='missing').length,checked=confirmed+missing,pct=inventoryRecords.length?Math.round(checked/inventoryRecords.length*100):0;$('inventory-summary').textContent=started?`Conferência ${currentSystem} iniciada em ${formattedDate(startedAt)} - ${checked}/${inventoryRecords.length} verificados (apenas CBSL).`:`Inicie uma conferência ${currentSystem}. Apenas são apresentados equipamentos alocados à CBSL.`;$('inventory-progress').innerHTML=started?`<div class="progress-track"><i style="width:${pct}%"></i></div><p>${pct}% concluído · ${confirmed} confirmados · ${missing} em falta</p>`:'';$('inventory-list').innerHTML=started?inventoryRecords.map(r=>`<div class="inventory-item ${r.inventoryStatus}"><div><strong>Rádio ${escapeHtml(r.portableNumber||'sem Nº')}</strong> · ${escapeHtml(r.type)} · ${escapeHtml(r.location)}<br><small>${escapeHtml(r.brand)} ${escapeHtml(r.model)}${r.system==='SIRESP'?` · ISSI ${escapeHtml(r.issi)}`:''}</small></div><div class="inventory-actions"><button class="secondary" data-inventory="pending" data-id="${r.id}">Por verificar</button><button class="primary" data-inventory="confirmed" data-id="${r.id}">Confirmado</button><button class="danger" data-inventory="missing" data-id="${r.id}">Em falta</button></div></div>`).join(''):'<p class="empty">Nenhuma conferência ativa.</p>'}
  function renderAll(){updateSystemUi();updateFilterOptions();renderList();renderDashboard();renderInventory();renderSecurity()}

  const CONSULTATION_FIELDS=['portableNumber','type','issi','serialNumber','brand','model','allocatedTo','network','status','location'];

  function consultationPayload(){const publicRecords=records.filter(r=>r.system==='SIRESP').map(r=>Object.fromEntries(CONSULTATION_FIELDS.map(key=>[key,String(r[key]||'').trim()]))).sort((a,b)=>a.portableNumber.localeCompare(b.portableNumber,'pt',{numeric:true,sensitivity:'base'}));return{application:'CBSLeiria Consulta SIRESP',schemaVersion:1,exportedAt:now(),recordCount:publicRecords.length,records:publicRecords}}
  function base64Utf8(value){const bytes=new TextEncoder().encode(value);let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary)}
  function openPublishDialog(){const token=localStorage.getItem(GITHUB_TOKEN_KEY)||'',repository=localStorage.getItem(GITHUB_REPOSITORY_KEY)||'jpleiria/radios_siresp_consulta';$('github-token').value=token;$('github-repository').value=repository;$('publish-dialog').showModal()}
  function removeGithubToken(){localStorage.removeItem(GITHUB_TOKEN_KEY);$('github-token').value='';show('Token de publicação removido deste navegador.')}
  async function publishConsultation(){if(!await ensureUnlocked())return;const token=$('github-token').value.trim(),repository=$('github-repository').value.trim().replace(/^https?:\/\/github\.com\//i,'').replace(/\/$/,'');if(!token){show('Introduza o token de publicação do GitHub.',true);return}if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository)){show('Indique o repositório no formato utilizador/repositório.',true);return}const button=$('confirm-publish'),payload=consultationPayload(),url=`https://api.github.com/repos/${repository}/contents/dados-siresp.json`;button.disabled=true;button.textContent='A publicar…';try{let sha;const current=await fetch(url,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'}});if(current.ok)sha=(await current.json()).sha;else if(current.status!==404)throw new Error(`GitHub respondeu ${current.status}`);const response=await fetch(url,{method:'PUT',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({message:`Atualizar dados SIRESP (${payload.recordCount} rádio(s))`,content:base64Utf8(JSON.stringify(payload,null,2)),...(sha?{sha}:{})})});if(!response.ok){const details=await response.json().catch(()=>null);throw new Error(details?.message||`GitHub respondeu ${response.status}`)}localStorage.setItem(GITHUB_TOKEN_KEY,token);localStorage.setItem(GITHUB_REPOSITORY_KEY,repository);$('publish-dialog').close();show(`Consulta publicada com ${payload.recordCount} rádio(s) SIRESP.`)}catch(error){show(`Não foi possível publicar: ${error.message||'erro de ligação'}.`,true)}finally{button.disabled=false;button.textContent='Publicar agora'}}

  function resetEditor(){form.reset();$('record-id').value='';$('form-title').textContent=`Registar equipamento ${currentSystem}`;$('save-button').textContent='Guardar equipamento';$('cancel-edit').classList.add('hidden');updateSystemUi();setTimeout(typePlaceholders,0)}
  function edit(id){const r=records.find(x=>x.id===id);if(!r)return;if(r.system!==currentSystem){currentSystem=r.system;settings.currentSystem=currentSystem;saveSettings()}FORM_FIELDS.forEach(k=>$(k).value=r[k]||'');$('record-id').value=id;$('form-title').textContent=r.portableNumber?`Editar equipamento ${r.system} - Rádio Nº ${r.portableNumber}`:`Editar equipamento ${r.system} sem Rádio Nº`;$('save-button').textContent='Guardar alterações';$('cancel-edit').classList.remove('hidden');updateSystemUi();typePlaceholders();setTab('form-panel');window.scrollTo({top:0,behavior:'smooth'})}
  const LABELS={portableNumber:'Rádio Nº',type:'Tipo',issi:'ISSI',serialNumber:'S/N',brand:'Marca',model:'Modelo',brandModel:'Marca / Modelo (anterior)',allocatedTo:'Alocado a',network:'Redes',status:'Estado',location:'Localização / Viatura',lastMaintenance:'Última manutenção',nextMaintenance:'Próxima revisão',notes:'Notas'};
  function makeQr(record){try{const qr=qrcode(0,'M'),base=location.href.split('#')[0];qr.addData(`${base}#radio=${encodeURIComponent(record.id)}`);qr.make();return qr.createDataURL(5,4)}catch{return''}}
  function renderFaults(record){$('fault-list').innerHTML=record.faults.length?record.faults.map(f=>`<div class="fault-entry ${f.status==='Resolvida'?'resolved':''}"><strong>${escapeHtml(f.status)} - ${formattedDate(f.date,false)}</strong><small>${escapeHtml(f.description)}</small>${f.provider?`<small>Entidade: ${escapeHtml(f.provider)}</small>`:''}${f.resolution?`<small>Resolução: ${escapeHtml(f.resolution)}</small>`:''}${f.returnDate?`<small>Retorno: ${formattedDate(f.returnDate,false)}</small>`:''}</div>`).join(''):'<p>Sem avarias registadas.</p>'}
  function view(id){const r=records.find(x=>x.id===id);if(!r)return;currentDetailId=id;$('detail-content').innerHTML=`<dl class="detail-grid"><div><dt>Sistema</dt><dd>${r.system}</dd></div>${fieldsForSystem(r.system).map(k=>`<div><dt>${LABELS[k]}</dt><dd>${k==='status'?`<span class="status ${statusClass(r[k])}">${escapeHtml(r[k])}</span>`:k==='type'?`<span class="type-badge">${typeIconHtml(r[k])} ${escapeHtml(r[k])}</span>`:k.includes('Maintenance')?formattedDate(r[k],false):escapeHtml(r[k]||'—')}</dd></div>`).join('')}</dl>`;const qr=makeQr(r);$('qr-container').innerHTML=qr?`<img class="qr-image" src="${qr}" alt="QR do equipamento">`:'';renderFaults(r);$('history-list').innerHTML=r.history.length?r.history.map(h=>`<li><strong>${escapeHtml(h.action)}</strong><time>${formattedDate(h.at)}</time>${h.changes?.map(c=>`<div>${escapeHtml(LABELS[c.field]||c.field)}: “${escapeHtml(c.from||'—')}” → “${escapeHtml(c.to||'—')}”</div>`).join('')||''}</li>`).join(''):'<li>Sem eventos registados.</li>';$('detail-dialog').showModal()}

  function download(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function timestampName(){return today()}
  function csvEscape(value){const s=String(value??'');return/[;"\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
  function selectedColumns(system=currentSystem){const available=columnsForSystem(system),keys=(settings.exportColumnsBySystem?.[system]||settings.exportColumns||DEFAULT_COLUMNS).filter(k=>available.some(c=>c.key===k)),selected=available.filter(c=>keys.includes(c.key));return selected.length?selected:available.slice(0,Math.min(8,available.length))}
  function exportCsv(){const cols=selectedColumns(),csv=[cols.map(c=>c.label).join(';'),...filtered().map(r=>cols.map(c=>csvEscape(r[c.key])).join(';'))].join('\r\n');download(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`radios-${currentSystem.toLowerCase()}-${timestampName()}.csv`);show(`CSV ${currentSystem} exportado com sucesso.`)}
  function exportJson(){settings.lastBackup=now();saveSettings();download(new Blob([JSON.stringify({application:'Registo Rádios Comunicações SIRESP/ROB',version:5,exportedAt:now(),records,settings},null,2)],{type:'application/json'}),`copia-radios-siresp-rob-${timestampName()}.json`);renderDashboard();show('Cópia de segurança integral criada.')}
  function exportConsultationJson(){const payload=consultationPayload();download(new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),'dados-siresp.json');show(`JSON de consulta criado com ${payload.recordCount} rádio(s) SIRESP.`)}
  function filterDescription(){const map=[['filter-search','Pesquisa'],['filter-type','Tipo'],['filter-status','Estado'],['filter-location','Localização'],['filter-allocated','Alocado'],['filter-brand','Marca'],['filter-model','Modelo'],['filter-network','Redes']];const applied=map.map(([id,label])=>[$(id).value.trim(),label]).filter(x=>x[0]).map(([v,l])=>`${l}: ${v}`);return applied.length?applied.join(' | '):'Sem filtros aplicados'}
  async function logoJpeg(){const image=document.querySelector('.logo');try{await image.decode()}catch{}const c=document.createElement('canvas');c.width=110;c.height=110;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,110,110);ctx.drawImage(image,0,0,110,110);return{data:atob(c.toDataURL('image/jpeg',.9).split(',')[1]),width:110,height:110}}
  function pdfText(value){return String(value??'').replace(/[–—]/g,'-').replace(/…/g,'...').replace(/[\\()]/g,'\\$&').replace(/[\r\n]+/g,' ')}
  function trimPdf(value,n){const s=String(value??'');return s.length>n?`${s.slice(0,Math.max(0,n-3))}...`:s}
  function finishPdf(objects,filename){let out='%PDF-1.4\n%âãÏÓ\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=out.length;const obj=objects[i];if(obj&&typeof obj==='object'){const d=obj.image.data;out+=`${i} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${obj.image.width} /Height ${obj.image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${d.length} >>\nstream\n${d}\nendstream\nendobj\n`}else out+=`${i} 0 obj\n${obj}\nendobj\n`}const xref=out.length;out+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const bytes=new Uint8Array(out.length);for(let i=0;i<out.length;i++)bytes[i]=out.charCodeAt(i)&255;download(new Blob([bytes],{type:'application/pdf'}),filename)}
  function wrapPdf(value,width,size){
    const ctx=document.createElement('canvas').getContext('2d');ctx.font=`${size}px Arial`;
    const fits=text=>ctx.measureText(text).width<=width-2,lines=[];
    for(const paragraph of String(value??'').replace(/\r\n?/g,'\n').split('\n')){
      let rest=paragraph;
      while(!fits(rest)&&rest.length>1){let at=1;while(at<rest.length&&fits(rest.slice(0,at+1)))at++;const space=rest.lastIndexOf(' ',at);if(space>0)at=space;lines.push(rest.slice(0,at));rest=rest.slice(at);if(rest.startsWith(' '))rest=rest.slice(1)}
      lines.push(rest);
    }
    return lines;
  }
  function tablePdf(cols,rows,title,filename,image=null,description=''){
    const pageWidth=842,pageHeight=595,margin=32,tableWidth=778,size=8,lineHeight=11;
    const weights=cols.map(c=>({location:2,serialNumber:1.5,notes:2.5,value:5}[c.key]||1)),total=weights.reduce((a,b)=>a+b,0),widths=weights.map(w=>tableWidth*w/total);
    const headers=cols.map((c,i)=>wrapPdf(c.label,widths[i]-8,size)),headerHeight=Math.max(...headers.map(x=>x.length))*lineHeight+10;
    const pages=[];let commands='',y=0;
    const text=(value,x,y,font=size)=>`BT /F1 ${font} Tf ${x} ${y} Td (${pdfText(value)}) Tj ET\n`;
    function cells(values,height,header=false){let x=margin;values.forEach((lines,i)=>{commands+=`${header?'0.16 0.20 0.24':'0.92 0.94 0.96'} rg ${x} ${y-height} ${widths[i]-1} ${height-1} re f\n${header?'1 1 1':'0.1 0.13 0.17'} rg\n`;lines.forEach((line,j)=>commands+=text(line,x+4,y-12-j*lineHeight));x+=widths[i]});y-=height}
    function newPage(){if(commands)pages.push(commands);commands=image?'q 40 0 0 40 32 535 cm /Im1 Do Q\n':'';commands+='0.1 0.13 0.17 rg\n'+text(title,82,560,15)+text('CBSLeiria',82,542,10);y=518;const meta=wrapPdf(description,tableWidth,7);meta.forEach(line=>{commands+=text(line,margin,y,7);y-=10});y-=6;cells(headers,headerHeight,true)}
    newPage();
    const fullCapacity=Math.floor((y-40-8)/lineHeight);
    for(const row of rows){const values=cols.map((c,i)=>wrapPdf(row[c.key],widths[i]-8,size));let offset=0,count=Math.max(...values.map(v=>v.length));
      if(count<=fullCapacity&&count*lineHeight+8>y-40)newPage();
      while(offset<count){let capacity=Math.floor((y-40-8)/lineHeight);if(capacity<1){newPage();capacity=Math.floor((y-40-8)/lineHeight)}const take=Math.min(count-offset,capacity);cells(values.map(v=>v.slice(offset,offset+take)),take*lineHeight+8);offset+=take;if(offset<count)newPage()}
    }
    pages.push(commands);
    const objects=[null,'<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map((_,i)=>`${5+i*2} 0 R`).join(' ')}] >>`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',image?{image}:'<< >>'];
    pages.forEach((content,i)=>{const pn=5+i*2,cn=pn+1;content+='0.1 0.13 0.17 rg\n'+text(`Página ${i+1} de ${pages.length}`,margin,22);objects[pn]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R >>${image?' /XObject << /Im1 4 0 R >>':''} >> /Contents ${cn} 0 R >>`;objects[cn]=`<< /Length ${content.length} >>\nstream\n${content}endstream`});
    finishPdf(objects,filename);
  }
  async function exportPdf(){const list=filtered();if(!list.length){show('Não existem registos para incluir no PDF.',true);return}let image=null;try{image=await logoJpeg()}catch{}tablePdf(selectedColumns(),list,`Registo Rádios Comunicações ${currentSystem}`,`listagem-radios-${currentSystem.toLowerCase()}-${timestampName()}.pdf`,image,`Emitido: ${formattedDate(now())} | ${list.length} equipamento(s) | ${filterDescription()}`);show(`PDF ${currentSystem} criado com sucesso.`)}
  function exportIndividualPdf(){const r=records.find(x=>x.id===currentDetailId);if(!r)return;const rows=[{field:'Sistema',value:r.system},...columnsForSystem(r.system).map(c=>({field:c.label,value:r[c.key]})),...r.faults.map(f=>({field:`Avaria ${formattedDate(f.date,false)}`,value:`${f.status}: ${f.description}\nEntidade: ${f.provider||''}\nRetorno: ${f.returnDate||''}\nResolução: ${f.resolution||''}`}))];tablePdf([{key:'field',label:'Campo'},{key:'value',label:'Conteúdo'}],rows,`Ficha do Rádio ${r.portableNumber||r.type}`,`ficha-radio-${r.system.toLowerCase()}-${r.portableNumber}-${timestampName()}.pdf`)}


  function parseCsv(text){const first=(text.split(/\r?\n/)[0]||''),sep=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===sep&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
  async function parseXlsx(file){const zip=await JSZip.loadAsync(await file.arrayBuffer()),shared=[];if(zip.file('xl/sharedStrings.xml')){const doc=new DOMParser().parseFromString(await zip.file('xl/sharedStrings.xml').async('text'),'application/xml');[...doc.getElementsByTagName('si')].forEach(si=>shared.push([...si.getElementsByTagName('t')].map(t=>t.textContent).join('')))}const wb=new DOMParser().parseFromString(await zip.file('xl/workbook.xml').async('text'),'application/xml'),sheet=wb.getElementsByTagName('sheet')[0],rid=sheet?.getAttribute('r:id'),rels=new DOMParser().parseFromString(await zip.file('xl/_rels/workbook.xml.rels').async('text'),'application/xml'),rel=[...rels.getElementsByTagName('Relationship')].find(x=>x.getAttribute('Id')===rid),target=rel?.getAttribute('Target')||'worksheets/sheet1.xml',path=target.startsWith('/')?target.slice(1):`xl/${target.replace(/^\.\//,'')}`,xml=await zip.file(path).async('text'),doc=new DOMParser().parseFromString(xml,'application/xml'),rows=[];[...doc.getElementsByTagName('row')].forEach(rowEl=>{const row=[];[...rowEl.getElementsByTagName('c')].forEach(c=>{const ref=c.getAttribute('r')||'A1';let col=0;for(const ch of ref.match(/[A-Z]+/)[0])col=col*26+ch.charCodeAt(0)-64;const type=c.getAttribute('t'),v=c.getElementsByTagName('v')[0]?.textContent||'',inline=[...c.getElementsByTagName('t')].map(t=>t.textContent).join('');row[col-1]=type==='s'?shared[Number(v)]||'':type==='inlineStr'?inline:v});rows.push(row.map(x=>x??''))});return rows}
  function importedRecords(rows){if(rows.length<2)return[];const headers=rows[0].map(normalized),find=(aliases)=>headers.findIndex(h=>aliases.some(a=>h===normalized(a))),indexes={portableNumber:find(['Rádio Nº','Portátil Nº','Radio']),type:find(['Tipo']),issi:find(['ISSI']),serialNumber:find(['S/N','SN','Número de série']),brand:find(['Marca']),model:find(['Modelo']),brandModel:find(['Marca / Modelo']),allocatedTo:find(['Alocado','Alocado a']),network:find(['Redes','Rede']),status:find(['Estado']),location:find(['Localização','Localização / Viatura']),notes:find(['Notas']),lastMaintenance:find(['Última manutenção']),nextMaintenance:find(['Próxima revisão'])};return rows.slice(1).map(row=>{const get=k=>indexes[k]>=0?String(row[indexes[k]]??'').trim():'';const legacy=splitBrandModel(get('brandModel'));return normalizeRecord({id:uid(),system:currentSystem,portableNumber:get('portableNumber'),type:get('type'),issi:currentSystem==='ROB'?'':get('issi'),serialNumber:get('serialNumber'),brand:get('brand')||legacy.brand,model:get('model')||legacy.model,allocatedTo:get('allocatedTo'),network:get('network'),status:get('status'),location:get('location'),notes:get('notes'),lastMaintenance:get('lastMaintenance'),nextMaintenance:get('nextMaintenance'),createdAt:now(),updatedAt:now(),history:[{at:now(),action:`Importado de ficheiro para ${currentSystem}`,changes:[]}]})}).filter(r=>r.serialNumber&&(r.system==='ROB'||r.issi)&&(!usesRadioNumber(r)||r.portableNumber))}
  async function importTable(file){if(!await ensureUnlocked())return;try{const rows=file.name.toLowerCase().endsWith('.xlsx')?await parseXlsx(file):parseCsv(await file.text()),incoming=importedRecords(rows);let added=0,skipped=0;for(const r of incoming){if(uniqueError(r,'')){skipped++;continue}records.push(r);added++}saveRecords();show(`Importação concluída: ${added} adicionados, ${skipped} duplicados ignorados.`)}catch(error){show(`Não foi possível importar o ficheiro: ${error.message||'formato inválido'}.`,true)}}

  function openColumns(){const selected=new Set(settings.exportColumnsBySystem?.[currentSystem]||settings.exportColumns||DEFAULT_COLUMNS);$('column-options').innerHTML=columnsForSystem().map(c=>`<label><input type="checkbox" value="${c.key}" ${selected.has(c.key)?'checked':''}> ${c.label}</label>`).join('');$('columns-dialog').showModal()}
  function saveColumns(){const keys=[...$('column-options').querySelectorAll('input:checked')].map(x=>x.value);if(!keys.length){show('Selecione pelo menos uma coluna.',true);return}settings.exportColumnsBySystem={...(settings.exportColumnsBySystem||{}),[currentSystem]:keys};saveSettings();$('columns-dialog').close();show(`Colunas de exportação ${currentSystem} atualizadas.`)}
  function printQr(){const r=records.find(x=>x.id===currentDetailId),src=r&&makeQr(r);if(!r||!src)return;const w=window.open('','_blank','width=500,height=650');if(!w){show('O navegador bloqueou a janela de impressão.',true);return}w.document.write(`<!doctype html><title>Etiqueta Rádio ${escapeHtml(r.portableNumber)}</title><style>body{text-align:center;font-family:Arial;padding:25px}.label{border:2px solid #111;padding:18px;display:inline-block}img{width:260px}.n{font-size:26px;font-weight:bold}</style><div class="label"><div class="n">Rádio ${escapeHtml(r.portableNumber)}</div><p>${escapeHtml(r.type)} · ${escapeHtml(r.brand)} ${escapeHtml(r.model)}</p><img src="${src}">${r.system==='SIRESP'?`<p>ISSI ${escapeHtml(r.issi)}</p>`:''}<strong>CBSLeiria · ${r.system}</strong></div><script>onload=()=>print()<\/script>`);w.document.close()}

  form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity()||!await ensureUnlocked())return;const data=valuesFromForm(),id=$('record-id').value,error=uniqueError(data,id);if(error){show(error,true);return}if(id){const r=records.find(x=>x.id===id),changes=FORM_FIELDS.filter(k=>r[k]!==data[k]).map(k=>({field:k,from:r[k],to:data[k]}));Object.assign(r,data,{updatedAt:now()});if(changes.length)appendHistory(r,'Alteração de equipamento',changes)}else{const r=normalizeRecord({id:uid(),...data,createdAt:now(),updatedAt:now(),history:[],faults:[]});appendHistory(r,'Equipamento registado');records.unshift(r)}saveRecords();resetEditor();show(id?'Equipamento atualizado.':'Equipamento registado com sucesso.')});
  form.addEventListener('reset',()=>setTimeout(()=>{updateSystemUi();typePlaceholders()},0));
  body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)view(b.dataset.view);if(b.dataset.edit)edit(b.dataset.edit);if(b.dataset.delete){pendingDelete=b.dataset.delete;$('confirm-dialog').showModal()}});
  document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.panel)));document.querySelectorAll('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{sort={key:th.dataset.sort,dir:sort.key===th.dataset.sort?-sort.dir:1};renderList()}));
  ['filter-search','filter-status','filter-location','filter-allocated','filter-brand','filter-model','filter-network'].forEach(id=>$(id).addEventListener(id==='filter-status'?'change':'input',renderList));['change','input'].forEach(ev=>$('filter-type').addEventListener(ev,()=>{updateTypePreview('filter-type','filter-type-icon-preview');renderList()}));
  $('clear-filters').addEventListener('click',()=>{clearFilters();renderList()});$('type').addEventListener('change',typePlaceholders);$('allocatedTo').addEventListener('change',updateAllocationRules);$('cancel-edit').addEventListener('click',resetEditor);document.querySelectorAll('button[data-system]').forEach(b=>b.addEventListener('click',()=>switchSystem(b.dataset.system)));
  $('export-csv').addEventListener('click',exportCsv);$('export-json').addEventListener('click',exportJson);$('export-consultation-json').addEventListener('click',exportConsultationJson);$('publish-consultation').addEventListener('click',openPublishDialog);$('confirm-publish').addEventListener('click',publishConsultation);$('remove-github-token').addEventListener('click',removeGithubToken);document.querySelectorAll('[data-close-publish]').forEach(b=>b.addEventListener('click',()=>$('publish-dialog').close()));$('export-pdf').addEventListener('click',()=>exportPdf().catch(()=>show('Não foi possível criar o PDF.',true)));$('column-settings').addEventListener('click',openColumns);$('save-columns').addEventListener('click',saveColumns);document.querySelectorAll('[data-close-columns]').forEach(b=>b.addEventListener('click',()=>$('columns-dialog').close()));
  $('import-table').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';if(file)importTable(file)});
  $('import-json').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file||!await ensureUnlocked())return;try{const parsed=JSON.parse(await file.text());let incoming=Array.isArray(parsed)?parsed:parsed.records;if(!Array.isArray(incoming))throw new Error;if(!confirm(`Restaurar ${incoming.length} equipamento(s)? Os dados atuais serão substituídos.`))return;records=incoming.map(normalizeRecord);if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed)&&parsed.settings&&typeof parsed.settings==='object'){const imported=parsed.settings;settings={...settings,...imported,exportColumnsBySystem:{...settings.exportColumnsBySystem,...(imported.exportColumnsBySystem||{})},inventoryStartedAtBySystem:{...settings.inventoryStartedAtBySystem,...(imported.inventoryStartedAtBySystem||{})}};settings.currentSystem=SYSTEMS.includes(settings.currentSystem)?settings.currentSystem:'SIRESP';currentSystem=settings.currentSystem;saveSettings()}saveRecords();resetEditor();show('Cópia de segurança restaurada.')}catch{show('Cópia JSON inválida.',true)}});
  $('confirm-delete').addEventListener('click',async()=>{if(!pendingDelete||!await ensureUnlocked(true))return;records=records.filter(r=>r.id!==pendingDelete);pendingDelete=null;$('confirm-dialog').close();saveRecords();show('Equipamento eliminado.')});$('cancel-delete').addEventListener('click',()=>{$('confirm-dialog').close();pendingDelete=null});
  document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>$('detail-dialog').close()));$('print-qr').addEventListener('click',printQr);$('individual-pdf').addEventListener('click',exportIndividualPdf);$('add-fault').addEventListener('click',()=>{$('fault-form').reset();$('fault-date').value=today();$('fault-dialog').showModal()});document.querySelectorAll('[data-close-fault]').forEach(b=>b.addEventListener('click',()=>$('fault-dialog').close()));
  $('fault-form').addEventListener('submit',async e=>{e.preventDefault();if(!await ensureUnlocked())return;const r=records.find(x=>x.id===currentDetailId);if(!r)return;r.faults.unshift({id:uid(),date:$('fault-date').value,status:$('fault-status').value,description:$('fault-description').value.trim(),provider:$('fault-provider').value.trim(),returnDate:$('fault-return-date').value,resolution:$('fault-resolution').value.trim()});if($('fault-status').value!=='Resolvida')r.status='Manutenção';appendHistory(r,'Avaria/reparação registada');$('fault-dialog').close();saveRecords();view(r.id);show('Avaria/reparação registada.')});
  $('start-inventory').addEventListener('click',async()=>{if(!await ensureUnlocked()||!confirm(`Iniciar uma nova conferência ${currentSystem}? O estado da conferência anterior será limpo.`))return;activeRecords().filter(r=>r.allocatedTo==='CBSL').forEach(r=>r.inventoryStatus='pending');settings.inventoryStartedAtBySystem[currentSystem]=now();saveSettings();saveRecords()});$('clear-inventory').addEventListener('click',async()=>{if(!settings.inventoryStartedAtBySystem[currentSystem]||!await ensureUnlocked())return;settings.inventoryStartedAtBySystem[currentSystem]=null;saveSettings();renderInventory()});$('inventory-list').addEventListener('click',async e=>{const b=e.target.closest('[data-inventory]');if(!b||!await ensureUnlocked())return;const r=records.find(x=>x.id===b.dataset.id&&x.system===currentSystem&&x.allocatedTo==='CBSL');if(r){r.inventoryStatus=b.dataset.inventory;saveRecords()}});
  $('security-button').addEventListener('click',configureSecurity);
  if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});
  updateSystemUi();typePlaceholders();updateTypePreview('filter-type','filter-type-icon-preview');renderAll();const hashId=location.hash.match(/radio=([^&]+)/)?.[1];if(hashId){const id=decodeURIComponent(hashId);setTimeout(()=>{const r=records.find(x=>x.id===id);if(r){currentSystem=r.system;settings.currentSystem=currentSystem;saveSettings();clearFilters();renderAll();setTab('list-panel');view(id)}},0)}
})();
